### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KyGost** [KyGost/KySpace#1]
- [ ] Redo player positioning
  - [ ] Should allow for player to be on a given tile. Not necessarily in center of screen.
- [ ] Move tile drawing under assets
  - [ ] Tiles should accept modifiers for texture choice
- [ ] Make a simple method for adding tiles/resources
  - [ ] via CSV or macro
- [ ] Tile conversion via floats and whatnot (currently rounding errors cause issues)
- [ ] Force board to be drawn with a center tile
- [ ] Prevent player from walking on certain tiles (ie. Water)
- [ ] UI which shows standing coords
- [ ] UI which shows hovered tile coords
- [ ] Ability to interact with environment
  - [ ] Ability to cut down trees, pick up rocks
- [ ] Ability to save
  - [ ] Should be as a log of changes based on the seed, not a saved copy of the generated world
- [ ] Inventory
  - [ ] GUI
- [ ] Player skin changes (gathered assets already allow for this, just need to implement)
